### PR TITLE
Creates placeholder for empty table

### LINKED ISSUE #15: Add placeholder text when there are no dreams created yet
It should be simple text to hide empty space at second tab, when there are no dreams created yet

### PR DESCRIPTION
**Pull request by samgusa**
Created a placeholder when there is an empty table, from start and when last dream is deleted.

### CODE REVIEW

**Comment by ArtyomArtamonov** [comment]
Hi. I actually don't like this design. To help you, I'm [attaching a figma file](https://drive.google.com/file/d/1P2a_t8fVM0ANAs4LebVQySIYP25Lw6XR/view?usp=sharing) with design prototypes, you should use it to make it look more prettier (import that file in figma).

You can try adding an action when tapping this text to show user EditDreamViewController.

**Review by ArtyomArtamonov — CHANGES_REQUESTED** [review]
Comment about this changes is above

**Comment by samgusa** [comment]
I don't actually have figma. Can you send a snapshot please?

**Comment by ArtyomArtamonov** [comment]
> I don't actually have figma. Can you send a snapshot please?

You don't have to install figma, you can use it in your browser

https://www.figma.com

**Comment by samgusa** [comment]
I created a new pull request

**Pull request merged**
